# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TerrainZones
                                 A QGIS plugin
 This Plugin Identifies & Creates Sub-Irrigation Zones
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-10-14
        copyright            : (C) 2023 by FALASY Anamelechi
        email                : fvw.services@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'FALASY Anamelechi'
__date__ = '2023-10-14'
__copyright__ = '(C) 2023 by FALASY Anamelechi'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TerrainZones class from file TerrainZones.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TerrainZones import TerrainZonesPlugin
    return TerrainZonesPlugin(iface)
